### ISSUE TITLE
iOS 10 support

### ISSUE THREAD

**Issue by VictorSharov** [hackiftekhar/IQActionSheetPickerView#21]
Are you plan to add iOS 10 support? At this version of iOS bottom buttons located behind the screen edge.

**Comment by hackiftekhar** [comment]
Ok, I'll check it with iOS10

**Comment by hackiftekhar** [comment]
I checked but I didn't found any issues with iOS 10, there are only some issues with the toolbar bottons

**Comment by VictorSharov** [comment]
Hm... I have a problem on iPhone 6 with iOS 10. I attach screenshot with this error.
![img_2016-09-17 09 13 35](https://cloud.githubusercontent.com/assets/12421922/18606385/3288e3f4-7cb7-11e6-85a9-2a9505863b56.jpg)

**Comment by hackiftekhar** [comment]
You mean Cancel & done button are too close to the screen?

**Comment by VictorSharov** [comment]
Yes, margin too small

**Comment by hackiftekhar** [comment]
I think I've fixed it yesterday and pushed a new cocoapods version. Could you please check?

**Comment by VictorSharov** [comment]
Yes, now all right is OK, thank you :)
