### ISSUE TITLE
cancelButton and doneButton position not correct

### ISSUE THREAD

**Issue by zhouzhongguang** [hackiftekhar/IQActionSheetPickerView#24]
I drage IQActionSheetPickerView code to my project, and  copy this code after：
IQActionSheetPickerView *picker = [[IQActionSheetPickerView alloc] initWithTitle:@"" delegate:self];
    [picker setTitlesForComponents:@[@[@"First", @"Second", @"Third", @"Four", @"Five"]]];
    [picker show];

after run it, i found the cancelButton and doneButton frame not correct.

![2017-09-22 11 18 35](https://user-images.githubusercontent.com/10241716/30728038-ec4bda6e-9f87-11e7-9e38-f79900da058a.png)

**Comment by zhouzhongguang** [comment]
iOS11

**Comment by virginiapujols** [comment]
I updated to 1.0.7 and i'm using ios11 simulator. 
The toolbar is not showing, why?
![screen shot 2017-09-29 at 12 45 07 pm](https://user-images.githubusercontent.com/12927639/31026388-496a743a-a514-11e7-8213-3fb97e0afa0f.png)
