### ISSUE TITLE
toolbar not showing

### ISSUE THREAD

**Issue by virginiapujols** [hackiftekhar/IQActionSheetPickerView#25]
I updated to 1.0.7 and i'm using ios11 simulator.
The toolbar is not showing, why?

![screen shot 2017-09-29 at 12 45 07 pm](https://user-images.githubusercontent.com/12927639/31026523-c95eea9a-a514-11e7-8e1f-14bf7f88e4fc.png)

**Comment by hackiftekhar** [comment]
Can you please update to latest version of library. It does have some fixes.
