### ISSUE TITLE
reloadComponent doesn`t work

### ISSUE THREAD

**Issue by Fuhaiyu** [hackiftekhar/IQActionSheetPickerView#26]
First, I make a picker with 2 arrays like this "[self.picker setTitlesForComponents:@[self.provinces, self.cities]];"

Then, I want reload picker When I change the component and row like this "[self.picker reloadComponent:1];". But it does`t work.

How can I fix it?

**Comment by hackiftekhar** [comment]
You have to change the cities array each time a province is selected. You can observe change event with `actionSheetPickerView:didChangeRow:inComponent:` method and can write your own custom logic to handle your case.
