### ISSUE TITLE
iPhone X

### ISSUE THREAD

**Issue by brightsider** [hackiftekhar/IQActionSheetPickerView#27]
Please, add support of iPhone X

**Comment by brightsider** [comment]
<img width="510" alt="screen" src="https://user-images.githubusercontent.com/4996231/32148729-cdc16822-bd03-11e7-9ed6-d8d7e34db578.png">

**Comment by jevenson** [comment]
Can you explain what's wrong with your screen shot?

**Comment by brightsider** [comment]
Needs to add spacing to bottom.

**Comment by hackiftekhar** [comment]
Fixed and released 1.0.8.

**Comment by brightsider** [comment]
Spacing ok, but this zone is not swipes, but should by Apple Guidelines. Please, fix it :)
![footer](https://user-images.githubusercontent.com/4996231/32403003-5799394c-c139-11e7-8199-eda08eed5cb9.png)

**Comment by hackiftekhar** [comment]
Can you please explain more about the swipe you are talking about?

**Comment by brightsider** [comment]
https://developer.apple.com/ios/human-interface-guidelines/overview/iphone-x/

Avoid explicitly placing interactive controls at the very bottom of the screen and in corners. People use swipe gestures at the bottom edge of the display to access the Home screen and app switcher, and these gestures may cancel custom gestures you implement in this area. The far corners of the screen can be difficult areas for people to reach comfortably.

**Comment by brightsider** [comment]
Can't go to Home via iOS native gesture for iPhone X.

**Comment by hackiftekhar** [comment]
@brightsider actually that's out of control, I did the best I can do. Here are the technical details

**Comment by hackiftekhar** [comment]
@brightsider actually that's out of control, I did the best I can do. Here are the technical details:-
- PickerView actually present within a UIViewController.
- Picker and Toolbar is assigned to viewController.inputView and viewController.inputAccessoryView respectively.
- There is no extra gestures added by library.
- to show it, the library calls [viewController becomeFirstResponder]; to tell iOS to present it's inputView and inputAccessoryView and then iOS shows those two things which is the standard approach.

Did you find anything I might be missing or doing wrong here? I would be glad to hear @brightsider and eager to fix.

**Comment by brightsider** [comment]
@hackiftekhar PickerView put in UIView that has spacing between bottom constraints equals to safeAreaInset.bottom
