### ISSUE TITLE
Could you add a indexPath same as UITableView?

### ISSUE THREAD

**Issue by shengxianghong** [hackiftekhar/IQActionSheetPickerView#28]
![dc23b376-fd6d-4664-ba9e-acb295db5470](https://user-images.githubusercontent.com/13196098/32979241-69061c46-cc8c-11e7-999c-5715a3dc16d1.png)

**Comment by hackiftekhar** [comment]
Ahh, that's a great Idea. Thanks I'll modify it with as next major release

**Comment by hackiftekhar** [comment]
I've optimized it to either use Indexes or NSIndexPath. Please take a look at my latest commit. It might ease your task. Please also take a look at migration guide here https://github.com/hackiftekhar/IQActionSheetPickerView/wiki/IQActionSheetPickerView-2.0.0-Migration-Guide
