### ISSUE TITLE
ActionSheetPicker Title - Cancel - Done Button Titles - ActionToolBar Color

### ISSUE THREAD

**Issue by Reapert** [hackiftekhar/IQActionSheetPickerView#9]
First of all thanks for easy to use awesome control. 

However I really need an initialization method or a way to customize titles and colors of bar button items cancel and done. So I can use it in my localized application.

- (id)initWithTitle:(NSString *)title delegate:(id<IQActionSheetPickerViewDelegate>)delegate cancelButtonTitle:(NSString *)cancelButtonTitle destructiveButtonTitle:(NSString *)destructiveButtonTitle actionToolBarColor:(UIColor *)barColor actionButtonBarColor:(UIColor *)barButtonColor;

Something like this maybe ?

**Comment by akring** [comment]
I just created a pull request for this,check it later:)

**Comment by hackiftekhar** [comment]
Pull request merged!

**Comment by burakkoray** [comment]
Thanks for the great project
do we have any option to changedone and cancel button text I could not found how to change ?

**Comment by akring** [comment]
Of course you can,In IQActionSheetPickerView.m:

* Cancel Button
```objectivec
//  Create a cancel button to show on keyboard to resign it. Adding a selector to resign it.
            UIBarButtonItem *cancelButton = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemCancel target:self action:@selector(pickerCancelClicked:)];
            [items addObject:cancelButton];
```

* Done Button
```objectivec
//  Create a done button to show on keyboard to resign it. Adding a selector to resign it.
            UIBarButtonItem *doneButton =[[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemDone target:self action:@selector(pickerDoneClicked:)];
            [items addObject:doneButton];
```

Just use the style you want

**Comment by burakkoray** [comment]
I mean can I change the button title done and cancel . Can I write finish instead of done

**Comment by akring** [comment]
Sure,create a new UIBarButtonItem via:
```objectivec
//  Create a finish button to show on keyboard to resign it. Adding a selector to resign it.
UIBarButtonItem *finishButton = [[UIBarButtonItem alloc] initWithTitle:@"Finish" style:UIBarButtonItemStylePlain target:self action:@selector(pickerDoneClicked:)];
 [items addObject:finishButton];
```

Currently we can just modify title by hardcoding,you can create a pull request to add this feature:)
